version: '3.8'

services:
  api:
    build: .
    container_name: oxo-api
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - PORT=8080
      - GIN_MODE=release
      - DB_HOST=postgres
      - DB_PORT